spring:
    profiles:
        active:
            - dev
    jpa:
        hibernate:
            ddl-auto: none
    datasource:
        url: 'jdbc:postgresql://localhost:5432/server'
        username:
        password:
    liquibase:
        change-log: 'classpath:db/changelog/db.changelog-main.yaml'
        contexts: default
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: 'http://localhost:8081/realms/teach-me/protocol/openid-connect/certs'
logging:
    level:
        root: INFO
    file: log/application.log
